### ISSUE TITLE
Tindie Shop Inaccessible

### ISSUE THREAD

**Issue by rotanigroc** [dudanov/iot-uni-dongle#9]
Tindie Shop link appears to be broken:
https://www.tindie.com/products/dudanov/universal-iot-dongle/ returns a Tindie 404 page.

Searching for the store name "dudanov" shows both the store and product in the quick list but neither open.

**Comment by dudanov** [comment]
Due to the unleashed war in Ukraine, sanctions were imposed against Russia. Of course, I am against this madness. I wish peace in the whole world. Due to the restrictions imposed by PayPal, as the main payment system of the Tindie store, the store, in turn, restricted access to the pages of Russian sellers.
